# Mapping information per district/ward

## Imports

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
from earthquake_damage.data.main import reduce_memory_df

In [17]:
household_comp = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/processed_data/comp_data_household.csv')
attributes_map = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/raw_data/geographical/attributes_maps.csv')
geo_keys = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/raw_data/geographical/ward_vdcmun_district_name_mapping.csv')

In [67]:
district_vdc_keys = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/raw_data/geographical/District_VDC_codes_Nepal.csv')
wards_keys = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/raw_data/geographical/wards_attributes.csv')

In [18]:
household_comp = reduce_memory_df(household_comp)
attributes_map = reduce_memory_df(attributes_map)

Original memory usage of df is 251 MB
New memory usage of df is 56 MB
Original memory usage of df is 0 MB
New memory usage of df is 0 MB

In [19]:
display(attributes_map.head())
attributes_map.shape

,ID,PROVINCE,DISTRICT,UNIT_TYPE,UNIT_NAME,DISTRICT_C,SHAPE_LENG,SHAPE_AREA
0,12001,1,OKHALDHUNGA,Gaunpalika,Champadevi,12,67524.513063,1.269135e+08
1,12002,1,OKHALDHUNGA,Gaunpalika,Chisankhugadhi,12,59967.873321,1.119305e+08
2,12003,1,OKHALDHUNGA,Gaunpalika,Khijidemba,12,63964.120360,1.797693e+08
3,12004,1,OKHALDHUNGA,Gaunpalika,Likhu,12,54519.341217,8.803235e+07
4,12005,1,OKHALDHUNGA,Gaunpalika,Manebhanjyang,12,59119.757274,1.466087e+08

(114, 8)

In [27]:
attributes_map.UNIT_NAME.unique()

['Champadevi', 'Chisankhugadhi', 'Khijidemba', 'Likhu', 'Manebhanjyang', ..., 'Gorkha', 'Palungtar', 'Sahid Lakhan', 'Siranchok', 'Sulikot']
Length: 110
Categories (110, object): ['Aarughat', 'Ajirkot', 'Bagmati', 'Baiteshwor', ..., 'Tripura Sundari', 'Tripurasundari', 'Umakunda', 'Uttargaya']

In [20]:
display(household_comp.head())
household_comp.shape

,building_id,district_id,vdcmun_id,ward_id,count_floors_pre_eq,age_building,land_surface_condition,foundation_type,roof_type,ground_floor_type,...,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,household_id,gender_household_head,age_household_head,education_level_household_head,income_level_household,size_household
0,120101000011,12,1207,120703,1,9,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100001101,Male,31.0,Illiterate,0.0,3.0
1,120101000021,12,1207,120703,1,15,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100002101,Female,62.0,Illiterate,0.0,6.0
2,120101000031,12,1207,120703,1,20,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100003101,Male,51.0,Illiterate,0.0,13.0
3,120101000041,12,1207,120703,1,20,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100004101,Male,48.0,Illiterate,0.0,5.0
4,120101000051,12,1207,120703,1,30,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100005101,Male,70.0,Illiterate,0.0,8.0

(747137, 44)

In [59]:
districts = household_comp.district_id.unique()

In [62]:
districts

array([12, 20, 21, 22, 23, 24, 28, 29, 30, 31, 36], dtype=int8)

In [21]:
display(geo_keys.head())
geo_keys.shape

,ward_id,vdcmun_id,vdcmun_name,district_id,district_name
0,120101,1201,Champadevi Rural Municipality,12,Okhaldhunga
1,120102,1201,Champadevi Rural Municipality,12,Okhaldhunga
2,120103,1201,Champadevi Rural Municipality,12,Okhaldhunga
3,120104,1201,Champadevi Rural Municipality,12,Okhaldhunga
4,120105,1201,Champadevi Rural Municipality,12,Okhaldhunga

(949, 5)

In [28]:
geo_keys.vdcmun_name.unique()

array(['Champadevi Rural Municipality',
       'Chishankhu Gadhi Rural Municipality',
       'Khiji Demba Rural Municipality', 'Likhu Rural Municipality',
       'Manebhanjyang Rural Municipality', 'Molung Rural Municipality',
       'Siddhicharan Municipality', 'Sunkoshi Rural Municipality',
       'Dudhouli Municipality', 'Ghyanglekha Rural Municipality',
       'Golanjor Rural Municipality',
       'Hariharpurgaghi Rural Municipality', 'Kamalamai Municipality',
       'Marin Rural Municipality', 'Phikkal Rural Municipality',
       'Tinpatan Rural Municipality', 'Doramba Rural Municipality',
       'Gokulganga Rural Municipality', 'Khandadevi Rural Municipality',
       'Likhu Tamakoshi Rural Municipality', 'Manthali  Municipality',
       'Ramechhap Municipality', 'Sunapati Rural Municipality',
       'Umakunda Rural Municipality', 'Baitedhar Rural Municipality',
       'Bhimeshwor Municipality', 'Bigu Rural Municipality',
       'Gaurishankar Rural Municipality', 'Jiri Municipality',
       'Kalinchowk Rural Municipality', 'Melung Rural Municipality',
       'Shailung Rural Municipality', 'Tamakoshi Rural Municipality',
       'Bahrabise Municipality', 'Balephi Rural Municipality',
       'Bhotekoshi Rural Municipality',
       'Choutara Sangachowkgadhi Municipality',
       'Helambu Rural Municipality', 'Indrawoti Rural Municipality',
       'Jugal Rural Municipality', 'Langtang National Park',
       'Lisankhu Pakhar Rural Municipality', 'Melanchi Municipality',
       'Panchpokhari Thangpal Rural Municipality',
       'Tripurasundari Rural Municipality', 'Banepa Municipality',
       'Bethanchowk Rural Municipality', 'Bhumlu Rural Municipality',
       'Chauri Deurali Rural Municipality', 'Dhulikhel Municipality',
       'Khanikhola Rural Municipality', 'Mahabharat Rural Municipality',
       'Mandan Deupur Municipality', 'Namobuddha Municipality',
       'Panauti Municipality', 'Panchkhal Municipality',
       'Roshi Rural Municipality', 'Temal Rural Municipality',
       'Belkotgadhi Municipality', 'Bidur Municipality',
       'Dupcheshwor Rural Municipality', 'Kakani Rural Municipality',
       'Kispang Rural Municipality', 'Myagang Rural Municipality',
       'Panchakanya Rural Municipality', 'Shivapuri Rural Municipality',
       'Suryagadhi Rural Municipality', 'Tadi Rural Municipality',
       'Tarakeshwor Rural Municipality',
       'Aamachhodingmo Rural Municipality',
       'Gosaikunda Rural Municipality', 'Kalika Rural Municipality',
       'Naukunda Rural Municipality', 'Uttargaya Rural Municipality',
       'Benighat Rorang Rural Municipality', 'Dhunibenshi Municipality',
       'Gajuri Rural Municipality', 'Galchhi Rural Municipality',
       'Ganga Jamuna Rural Municipality', 'Jwalamukhi Rural Municipality',
       'Khaniyabas Rural Municipality',
       'Netrawati Dabajong Rural Municipality',
       'Neelakantha Municipality', 'Rubi Valley Rural Municipality',
       'Siddhalek Rural Municipality', 'Thakre Rural Municipality',
       'Bagmati Rural Municipality', 'Bakaiya Rural Municipality',
       'Bhimphedi Rural Municipality', 'Hetauda Sub-Metropolitian City',
       'Indrasarowar Rural Municipality', 'Kailash Rural Municipality',
       'Makawanpurgadhi Rural Municipality',
       'Manahari Rural Municipality', 'Parsa Wild Life Reserve',
       'Raksirang Rural Municipality', 'Thaha Municipality',
       'Aarughat Rural Municipality', 'Ajirkot Rural Municipality',
       'Barpak Sulikot Rural Municipality',
       'Bhimsen Thapa Rural Municipality',
       'Chumanubri Rural Municipality', 'Dharche Rural Municipality',
       'Gandaki Rural Municipality', 'Gorkha Municipality',
       'Palungtar Municipality', 'Shahid Lakhan Rural Municipality',
       'Siranchowk Rural Municipality'], dtype=object)

In [45]:
district_vdc_keys.head()

,District,Zone,Geographical Region,Region,District_code,VDC_name,VDC_code
0,Taplejung,Mechi,Mountain,Eastern,1,Ambegudin,1001
1,Taplejung,Mechi,Mountain,Eastern,1,Ankhop,1002
2,Taplejung,Mechi,Mountain,Eastern,1,Chaksibote,1003
3,Taplejung,Mechi,Mountain,Eastern,1,Change,1004
4,Taplejung,Mechi,Mountain,Eastern,1,Dhungesaghu,1005

In [52]:
district_vdc_keys.District_code.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75])

In [53]:
district_vdc_keys.District.unique()

array(['Taplejung', 'Panchthar', 'Ilam', 'Jhapa', 'Morang', 'Sunsari',
       'Dhankuta', 'Terhathum', 'Sankhuwasabha', 'Bhojpur', 'Solukhumbu',
       'Okhaldhunga', 'Khotang', 'Udayapur', 'Saptari', 'Siraha',
       'Dhanusa', 'Mahottari', 'Sarlahi', 'Sindhuli', 'Ramechhap',
       'Dolakha', 'Sindhupalchok', 'Kavre', 'Lalitpur', 'Bhaktapur',
       'Kathmandu', 'Nuwakot', 'Rasuwa', 'Dhading', 'Makwanpur',
       'Rautahat', 'Bara', 'Parsa', 'Chitawan', 'Gorkha', 'Lamjung',
       'Tanahu', 'Syangja', 'Kaski', 'Manang', 'Mustang', 'Myagdi',
       'Parbat', 'Baglung', 'Gulmi', 'Palpa', 'Nawalparasi', 'Rupandehi',
       'Kapilbastu', 'Arghakhanchi', 'Pyuthan', 'Rolpa', 'Rukum',
       'Salyan', 'Dang', 'Banke', 'Bardiya', 'Surkhet', 'Dailekh',
       'Jajarkot', 'Dolpa', 'Jumla', 'Kalikot', 'Mugu', 'Humla', 'Bajura',
       'Bajhang', 'Achham', 'Doti', 'Kailali', 'Kanchanpur', 'Dadeldhura',
       'Baitadi', 'Darchaula'], dtype=object)

In [66]:
# only show columns with district_code = 12
district_vdc_keys[district_vdc_keys['VDC_code'] == 12001]

,District,Zone,Geographical Region,Region,District_code,VDC_name,VDC_code
507,Okhaldhunga,Sagarmatha,Hill,Eastern,12,Andheri(Narayansthan),12001

In [68]:
wards_keys.head()

   WARD  PROVINCE  DISTRICT                        PALIKA         TYPE
0    10         1  DHANKUTA                  Sangurigadhi   Gaunpalika
1     9         1  DHANKUTA                  Sangurigadhi   Gaunpalika
2     7         1  DHANKUTA  Khalsa Chhintang Shahidbhumi   Gaunpalika
3     6         1  DHANKUTA  Khalsa Chhintang Shahidbhumi   Gaunpalika
4     7         1  DHANKUTA                     Mahalaxmi  Nagarpalika

In [72]:
wards_keys[wards_keys['DISTRICT'] == 'OKHALDHUNGA']

     WARD  PROVINCE     DISTRICT          PALIKA         TYPE
298     1         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
299     2         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
300     5         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
301     2         1  OKHALDHUNGA          Molung   Gaunpalika
302     7         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
303    10         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
304     6         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
305     8         1  OKHALDHUNGA      Khijidemba   Gaunpalika
306     8         1  OKHALDHUNGA      Champadevi   Gaunpalika
307     9         1  OKHALDHUNGA      Champadevi   Gaunpalika
308     7         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
309     8         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
310     3         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
311     6         1  OKHALDHUNGA           Likhu   Gaunpalika
312     7         1  OKHALDHUNGA           Likhu   Gaunpalika
313     4         1  OKHALDHUNGA          Molung   Gaunpalika
314     3         1  OKHALDHUNGA          Molung   Gaunpalika
315     6         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
316     9         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
317     3         1  OKHALDHUNGA      Champadevi   Gaunpalika
318     9         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
319    10         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
320     4         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
321     3         1  OKHALDHUNGA      Khijidemba   Gaunpalika
322     5         1  OKHALDHUNGA      Khijidemba   Gaunpalika
323     6         1  OKHALDHUNGA      Khijidemba   Gaunpalika
324     4         1  OKHALDHUNGA      Khijidemba   Gaunpalika
325     1         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
326     1         1  OKHALDHUNGA          Molung   Gaunpalika
327     9         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
328     8         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
329     7         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
330     5         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
331     1         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
332     5         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
333     6         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
334     3         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
335     3         1  OKHALDHUNGA           Likhu   Gaunpalika
336    11         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
337    12         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
338     1         1  OKHALDHUNGA      Champadevi   Gaunpalika
339     2         1  OKHALDHUNGA      Champadevi   Gaunpalika
340     7         1  OKHALDHUNGA          Molung   Gaunpalika
341     9         1  OKHALDHUNGA      Khijidemba   Gaunpalika
342     4         1  OKHALDHUNGA      Champadevi   Gaunpalika
343     5         1  OKHALDHUNGA      Champadevi   Gaunpalika
344     6         1  OKHALDHUNGA      Champadevi   Gaunpalika
345     7         1  OKHALDHUNGA      Champadevi   Gaunpalika
346     2         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
347     9         1  OKHALDHUNGA           Likhu   Gaunpalika
348     5         1  OKHALDHUNGA          Molung   Gaunpalika
349     1         1  OKHALDHUNGA      Khijidemba   Gaunpalika
350     2         1  OKHALDHUNGA      Khijidemba   Gaunpalika
351     8         1  OKHALDHUNGA          Molung   Gaunpalika
352    10         1  OKHALDHUNGA      Champadevi   Gaunpalika
353     4         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
354     5         1  OKHALDHUNGA  Chisankhugadhi   Gaunpalika
355     7         1  OKHALDHUNGA      Khijidemba   Gaunpalika
356     4         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
357     8         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
358     6         1  OKHALDHUNGA          Molung   Gaunpalika
359     1         1  OKHALDHUNGA           Likhu   Gaunpalika
360     2         1  OKHALDHUNGA           Likhu   Gaunpalika
361     3         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
362     4         1  OKHALDHUNGA        Sunkoshi   Gaunpalika
363     7         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
364     8         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
365     1         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
366     8         1  OKHALDHUNGA           Likhu   Gaunpalika
367     6         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
368     2         1  OKHALDHUNGA    Siddhicharan  Nagarpalika
369     3         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
370     2         1  OKHALDHUNGA   Manebhanjyang   Gaunpalika
371     4         1  OKHALDHUNGA           Likhu   Gaunpalika
372     5         1  OKHALDHUNGA           Likhu   Gaunpalika

In [71]:
wards_keys.DISTRICT.unique()

array(['DHANKUTA', 'MORANG', 'KHOTANG', 'OKHALDHUNGA', 'PANCHTHAR',
       'SOLUKHUMBU', 'UDAYAPUR', 'TERHATHUM', 'TAPLEJUNG',
       'SANKHUWASABHA', 'SUNSARI', 'JHAPA', 'BHOJPUR', 'ILAM', 'SAPTARI',
       'SIRAHA', 'DHADING', 'CHITAWAN', 'DOLAKHA', 'KABHREPALANCHOK',
       'LALITPUR', 'MAKAWANPUR', 'RASUWA', 'RAMECHHAP', 'SINDHUPALCHOK',
       'SINDHULI', 'BHAKTAPUR', 'BAGLUNG', 'ARGHAKHANCHI', 'GULMI',
       'GORKHA', 'KAPILBASTU', 'KASKI', 'PARBAT', 'NAWALPARASI', 'MYAGDI',
       'RUPANDEHI', 'SYANGJA', 'TANAHU', 'MUSTANG', 'PALPA', 'LAMJUNG',
       'BARDIYA', 'BANKE', 'DAILEKH', 'DANG', 'JAJARKOT', 'HUMLA',
       'DOLPA', 'KALIKOT', 'JUMLA', 'MUGU', 'PYUTHAN', 'SALYAN',
       'SURKHET', 'ROLPA', 'RUKUM', 'BAJURA', 'BAITADI', 'ACHHAM',
       'DARCHULA', 'DADELDHURA', 'DOTI', 'KANCHANPUR', 'KAILALI',
       'SARLAHI', 'RAUTAHAT', 'PARSA', 'NUWAKOT', 'MANANG', 'MAHOTTARI',
       'KATHMANDU', 'DHANUSHA', 'BAJHANG', 'BARA'], dtype=object)