# Convert user input into model input

In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
household_comp = pd.read_csv('/Users/chantalwuerschinger/code/chantalwuer/earthquake_damage/processed_data/comp_data_household.csv')

## User Input

In [17]:
district_id = 12
municipality_id = 1201
ward = 5


age = 5
floors = 2
superstructure = 5

In [27]:
# Determine superstructure kind
has_superstructure_adobe_mud = 0
has_superstructure_mud_mortar_stone = 0 
has_superstructure_stone_flag = 0 
has_superstructure_cement_mortar_stone = 0 
has_superstructure_mud_mortar_brick = 0 
has_superstructure_cement_mortar_brick = 0 
has_superstructure_timber = 0 
has_superstructure_bamboo = 0  
has_superstructure_rc_non_engineered = 0 
has_superstructure_rc_engineered = 0  
has_superstructure_other = 0

if superstructure == 0: 
    has_superstructure_adobe_mud = 1
elif superstructure == 1:
    has_superstructure_mud_mortar_stone = 1
elif superstructure == 2:
    has_superstructure_stone_flag = 1
elif superstructure == 3:
    has_superstructure_cement_mortar_stone = 1
elif superstructure == 4:
    has_superstructure_mud_mortar_brick = 1
elif superstructure == 5:
    has_superstructure_cement_mortar_brick = 1
elif superstructure == 6:
    has_superstructure_timber = 1
elif superstructure == 7:
    has_superstructure_bamboo = 1
elif superstructure == 8:
    has_superstructure_rc_non_engineered = 1
elif superstructure == 9:
    has_superstructure_rc_engineered = 1
elif superstructure == 10:
    has_superstructure_other = 1

### District & Municipalities Codes

In [28]:
district_codes = { 
        12:'Okhaldhunga',
        20:'Sindhuli',
        21:'Ramechhap',
        22:'Dolakha',
        23:'Sindhupalchok',
        24:'KABHREPALANCHOK',
        28:'Nuwakot',
        29:'Rasuwa',
        30:'Dhading',
        31:'Makawanpur',
        36:'Gorkha'
}

district_codes = {k: v.lower() for k, v in district_codes.items()}

In [29]:
municipality_codes = { 
        1201: 'Champadevi',
        1202: 'Chisankhugadhi',
        1203: 'Khijidemba',
        1204: 'Likhu',
        1205: 'Manebhanjyang',
        1206: 'Molung',
        1207: 'Siddhicharan',
        1208: 'Sunkoshi',
        2001: 'Dudhouli',
        2002: 'Ghyanglekha',
        2003: 'Golanjor',
        2004: 'Hariharpurgadhi',
        2005: 'Kamalamai',
        2006: 'Marin',
        2007: 'Phikkal',
        2008: 'Sunkoshi',
        2009: 'Tinpatan',
        2101: 'Doramba',
        2102: 'Gokulganga',
        2103: 'Khadadevi',
        2104: 'Likhu Tamakoshi',
        2105: 'Manthali',
        2106: 'Ramechhap',
        2107: 'Sunapati',
        2108: 'Umakunda',
        2201: 'baiteshwor',
        2202: 'Bhimeshwor',
        2203: 'Bigu',
        2204: 'Gaurishankar',
        2205: 'Jiri',
        2206: 'Kalinchok',
        2207: 'Melung',
        2208: 'Sailung',
        2209: 'Tamakoshi',
        2301: 'Barhabise',
        2302: 'Balefi',
        2303: 'Bhotekoshi',
        2304: 'Chautara sangachok gadhi',
        2305: 'Helambu',
        2306: 'Indrawati',
        2307: 'Jugal',
        2308: 'Langtang National Park',
        2309: 'lisangkhu pakhar',
        2310: 'Melamchi',
        2311: 'Panchpokhari Thangpal',
        2312: 'Sunkoshi',
        2313: 'Tripurasundari',
        2401: 'Banepa',
        2402: 'Bethanchowk',
        2403: 'Bhumlu',
        2404: 'Chaurideurali',
        2405: 'Dhulikhel',
        2406: 'Khanikhola',
        2407: 'Mahabharat',
        2408: 'Mandandeupur',
        2409: 'Namobuddha',
        2410: 'Panauti',
        2411: 'Panchkhal',
        2412: 'Roshi',
        2413: 'Temal',
        2801: 'Belkotgadhi',
        2802: 'Bidur',
        2803: 'Dupcheshwar',
        2804: 'Kakani',
        2805: 'Kispang',
        2807: 'Likhu',
        2808: 'Myagang',
        2809: 'Panchakanya',
        2810: 'Shivapuri',
        2811: 'Suryagadhi',
        2812: 'Tadi',
        2813: 'Tarakeshwor',
        2901: 'Aamachhodingmo',
        2902: 'Gosaikunda',
        2903: 'Kalika',
        2904: 'Naukunda',
        2905: 'Uttargaya',
        3001: 'Benighat Rorang',
        3002: 'Dhunibesi',
        3003: 'Gajuri',
        3004: 'Galchi',
        3005: 'Gangajamuna',
        3006: 'Jwalamukhi',
        3007: 'Khaniyabash',
        3008: 'Netrawati',
        3009: 'Nilakantha',
        3010: 'Rubi Valley',
        3011: 'Siddhalek',
        3012: 'Thakre',
        3013: 'Tripurasundari',
        3101: 'Bagmati',
        3102: 'Bakaiya',
        3103: 'Bhimphedi',
        3104: 'Hetauda',
        3105: 'Indrasarowar',
        3106: 'Kailash',
        3107: 'Makawanpurgadhi',
        3108: 'Manahari',
        3109: 'Parsa Wildlife Reserve',
        3110: 'Raksirang',
        3111: 'Thaha',
        3601: 'Aarughat',
        3602: 'Ajirkot',
        3603: 'Sulikot',
        3604: 'Bhimsen',
        3605: 'Chum nubri',
        3606: 'Dharche',
        3607: 'Gandaki',
        3608: 'Gorkha',
        3609: 'Palungtar',
        3610: 'Sahid lakhan',
        3611: 'Siranchok'
}

municipality_codes = {k: v.lower() for k, v in municipality_codes.items()}

In [30]:
superstructures = {
    0: 'has_superstructure_adobe_mud',
    1: 'has_superstructure_mud_mortar_stone',
    2: 'has_superstructure_stone_flag',
    3: 'has_superstructure_cement_mortar_stone',
    4: 'has_superstructure_mud_mortar_brick',
    5: 'has_superstructure_cement_mortar_brick',
    6: 'has_superstructure_timber',
    7: 'has_superstructure_bamboo', 
    8: 'has_superstructure_rc_non_engineered',
    9: 'has_superstructure_rc_engineered', 
    10: 'has_superstructure_other'
}

### Create ward_id

In [31]:
if ward < 10:
    ward_id = str(municipality_id) + '0' + str(ward)
else: 
    ward_id = str(municipality_id) + str(ward)

ward_id = int(ward_id)

## Create model input

In [32]:
household_comp.head()

,building_id,district_id,vdcmun_id,ward_id,count_floors_pre_eq,age_building,land_surface_condition,foundation_type,roof_type,ground_floor_type,...,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,household_id,gender_household_head,age_household_head,education_level_household_head,income_level_household,size_household
0,120101000011,12,1207,120703,1,9,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100001101,Male,31.0,Illiterate,Rs. 10 thousand,3.0
1,120101000021,12,1207,120703,1,15,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100002101,Female,62.0,Illiterate,Rs. 10 thousand,6.0
2,120101000031,12,1207,120703,1,20,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100003101,Male,51.0,Illiterate,Rs. 10 thousand,13.0
3,120101000041,12,1207,120703,1,20,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100004101,Male,48.0,Illiterate,Rs. 10 thousand,5.0
4,120101000051,12,1207,120703,1,30,Flat,Other,Bamboo/Timber-Light roof,Mud,...,0,0,0,0,12010100005101,Male,70.0,Illiterate,Rs. 10 thousand,8.0

In [33]:
household_comp.columns

Index(['building_id', 'district_id', 'vdcmun_id', 'ward_id',
       'count_floors_pre_eq', 'age_building', 'land_surface_condition',
       'foundation_type', 'roof_type', 'ground_floor_type', 'other_floor_type',
       'position', 'plan_configuration', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'damage_grade', 'legal_ownership_status', 'count_families',
       'has_secondary_use', 'has_secondary_use_agriculture',
       'has_secondary_use_hotel', 'has_secondary_use_rental',
       'has_secondary_use_institution', 'has_secondary_use_school',
       'has_secondary_use_industry', 'has_secondary_use_health_post',
       'has_secondary_use_gov_office', 'has_secondary_use_use_police',
       'has_secondary_use_other', 'household_id', 'gender_household_head',
       'age_household_head', 'education_level_household_head',
       'income_level_household', 'size_household'],
      dtype='object')

In [34]:
user_input = {'district_id': district_id, 
              'vdcmun_id' : municipality_id, 
              'ward_id': ward_id,
              'count_floors_pre_eq': floors,
              'age_building': age,
              'has_superstructure_adobe_mud' : has_superstructure_adobe_mud,
              'has_superstructure_mud_mortar_stone': has_superstructure_mud_mortar_stone,
              'has_superstructure_stone_flag': has_superstructure_stone_flag,
              'has_superstructure_cement_mortar_stone': has_superstructure_cement_mortar_stone,
              'has_superstructure_mud_mortar_brick': has_superstructure_mud_mortar_brick,
              'has_superstructure_cement_mortar_brick': has_superstructure_cement_mortar_brick,
              'has_superstructure_timber': has_superstructure_timber,
              'has_superstructure_bamboo': has_superstructure_bamboo, 
              'has_superstructure_rc_non_engineered': has_superstructure_rc_non_engineered,
              'has_superstructure_rc_engineered': has_superstructure_rc_engineered, 
              'has_superstructure_other': has_superstructure_other
              }

In [35]:
user_input

{'district_id': 12,
 'vdcmun_id': 1201,
 'ward_id': 120105,
 'count_floors_pre_eq': 2,
 'age_building': 5,
 'has_superstructure_adobe_mud': 0,
 'has_superstructure_mud_mortar_stone': 0,
 'has_superstructure_stone_flag': 0,
 'has_superstructure_cement_mortar_stone': 0,
 'has_superstructure_mud_mortar_brick': 0,
 'has_superstructure_cement_mortar_brick': 1,
 'has_superstructure_timber': 0,
 'has_superstructure_bamboo': 0,
 'has_superstructure_rc_non_engineered': 0,
 'has_superstructure_rc_engineered': 0,
 'has_superstructure_other': 0}

In [36]:
user_input_df = pd.DataFrame(user_input, index=[ward_id])
user_input_df

,district_id,vdcmun_id,ward_id,count_floors_pre_eq,age_building,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other
120105,12,1201,120105,2,5,0,0,0,0,0,1,0,0,0,0,0

In [37]:
to_determine = [
    'land_surface_condition',
    'foundation_type', 
    'roof_type', 
    'ground_floor_type', 
    'other_floor_type',
    'position', 
    'plan_configuration', 
    'legal_ownership_status', 
    'count_families',
    'has_secondary_use', 'has_secondary_use_agriculture',
    'has_secondary_use_hotel', 'has_secondary_use_rental',
    'has_secondary_use_institution', 'has_secondary_use_school',
    'has_secondary_use_industry', 'has_secondary_use_health_post',
    'has_secondary_use_gov_office', 'has_secondary_use_use_police',
    'has_secondary_use_other', 'household_id', 'gender_household_head',
    'age_household_head', 'education_level_household_head',
    'income_level_household', 'size_household']

In [38]:
agg_method = {'float64': 'mean', 'int64': 'mean', 'object':  pd.Series.mode}
data_grouped_wards = household_comp.groupby('ward_id').agg({k: agg_method[str(v)] for k, v in household_comp.dtypes.items()}).round(0)

data_grouped_wards.drop(user_input.keys(), axis=1, inplace=True)
data_grouped_wards.drop(['damage_grade'], axis=1, inplace=True)

In [39]:
data_grouped_wards.head()

,building_id,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,legal_ownership_status,count_families,...,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,household_id,gender_household_head,age_household_head,education_level_household_head,income_level_household,size_household
ward_id,,,,,,,,,,,,,,,,,,,,,
120101,1.234031e+11,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,1.234031e+13,Male,46.0,Non-formal education,Rs. 10 thousand,6.0
120102,1.234077e+11,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,1.234077e+13,Female,43.0,Illiterate,Rs. 10 thousand,6.0
120103,1.219049e+11,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,1.219049e+13,Male,46.0,Illiterate,Rs. 10 thousand,6.0
120104,1.213038e+11,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,1.213038e+13,Male,48.0,Illiterate,Rs. 10 thousand,6.0
120105,1.213060e+11,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Brick/Stone,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,1.213060e+13,Male,45.0,Illiterate,Rs. 10 thousand,5.0

In [40]:
# Get average data for chosen ward_id

remaining_data = data_grouped_wards.loc[ward_id]
remaining_data_df = pd.DataFrame(remaining_data).T
remaining_data_df

,building_id,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,legal_ownership_status,count_families,...,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,household_id,gender_household_head,age_household_head,education_level_household_head,income_level_household,size_household
120105,121306017381.0,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Brick/Stone,TImber/Bamboo-Mud,Not attached,Rectangular,Private,1.0,...,0.0,0.0,0.0,0.0,12130601738141.0,Male,45.0,Illiterate,Rs. 10 thousand,5.0

#### Put User input into shape

#### Get mode values for ward_id for all other features

#### Preprocess input

In [41]:
model_input = pd.concat([user_input_df, remaining_data_df], axis=1)
model_input

,district_id,vdcmun_id,ward_id,count_floors_pre_eq,age_building,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,...,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,household_id,gender_household_head,age_household_head,education_level_household_head,income_level_household,size_household
120105,12,1201,120105,2,5,0,0,0,0,0,...,0.0,0.0,0.0,0.0,12130601738141.0,Male,45.0,Illiterate,Rs. 10 thousand,5.0

In [49]:
model_input.shape

(1, 43)

In [44]:
model_input.columns

Index(['district_id', 'vdcmun_id', 'ward_id', 'count_floors_pre_eq',
       'age_building', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick', 'has_superstructure_timber',
       'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'building_id', 'land_surface_condition', 'foundation_type', 'roof_type',
       'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'legal_ownership_status', 'count_families',
       'has_secondary_use', 'has_secondary_use_agriculture',
       'has_secondary_use_hotel', 'has_secondary_use_rental',
       'has_secondary_use_institution', 'has_secondary_use_school',
       'has_secondary_use_industry', 'has_secondary_use_health_post',
       'has_secondary_use_gov_office', 'has_secondary_use_use_police',
       'has_secondary_use_other', 'household_id', 'gender_household_head',
       'age_household_head', 'education_level_household_head',
       'income_level_household', 'size_household'],
      dtype='object')

In [50]:
from earthquake_damage.data.model_input import get_model_input

In [51]:
output = get_model_input(district_id=12, municipality_id=1201, ward=5, age=5, floors=2, superstructure=5)
output.shape

(1, 83)

In [47]:
output.shape

(1, 83)